处理 Druid 版本导致的 MySQL 同步期间 java.lang.NoSuchFieldError: MYSQL
alibaba/otter pull request #1113
Opened 2023-09-14 13:51 UTC by quanllong

异常现象：MySQL数据同步过程中，pipeline 同步停止，延迟时间不断增大
日志显示：java.lang.NoSuchFieldError: MYSQL
修复手段：修改 Druid 版本和相关代码
#1068

2023-09-14 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/otter?pullRequest=1113) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/otter?pullRequest=1113) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/otter?pullRequest=1113) it.</sub>

2023-09-17 13:48 UTC, whhe requested changes

2023-09-17 13:48 UTC, whhe commented on node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java
> +import com.alibaba.druid.sql.ast.statement.*;
Do not use `*` in import statement.

2023-09-18 02:04 UTC, quanllong commented on node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java
> +import com.alibaba.druid.sql.ast.statement.*;
Fixed

2023-09-18 02:27 UTC, whhe approved these changes
LGTM, thanks for your contribution.

2023-09-18 02:27 UTC, merged